name: Open Journals PDF Generator

on:
  push:
    branches:
      - paper

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v1.0
        # with:
        #   paper-path: 'paper.md'
        #   journal: 'joss'
